services:
    db:
        image: postgres:17
        restart: always
        env_file:
            - .env
        command: postgres -c password_encryption=scram-sha-256
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./postgres-init:/docker-entrypoint-initdb.d

    backend:
        build: ./backend
        restart: always
        depends_on:
            - db
        env_file:
            - .env

    frontend:
        build: ./frontend
        restart: always
        depends_on:
            - backend

    nginx:
        image: nginx:stable-alpine3.21
        restart: always
        ports:
            - "80:80" # http
            - "443:443" # https
        volumes:
            - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on:
            - frontend
            - backend

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        # Sprawdzanie co 12h czy należy odnowić certyfikat
        command: renew --quiet

volumes:
    db-data:
